app.factory('ImgurFactory', function ($http) {
	return {
		getImages: function (which) {
			$http.defaults.headers.common.Authorization = 'Client-ID fec98667bde0380';
			return $http.get('https://api.imgur.com/3/gallery/r/' + which + 'porn/top/month')
				.then(function (response) {
					console.log(response.data)
					return response.data
				}, function (err) {
					console.log("error", err)
				})
		},
		categories: [{
			"name": "Earth"
		}, {
			"name": "Botanical"
		}, {
			"name": "Water"
		}, {
			"name": "Sea"
		}, {
			"name": "Sky"
		}, {
			"name": "Fire"
		}, {
			"name": "Desert"
		}, {
			"name": "Winter"
		}, {
			"name": "Autumn"
		}, {
			"name": "Weather"
		}, {
			"name": "Geology"
		}, {
			"name": "Space"
		}, {
			"name": "Beach"
		}, {
			"name": "Mushroom"
		}, {
			"name": "Spring"
		}, {
			"name": "Summer"
		}, {
			"name": "Lava"
		}, {
			"name": "Lake"
		}, {
			"name": "City"
		}, {
			"name": "Village"
		}, {
			"name": "Rural"
		}, {
			"name": "Architecture"
		}, {
			"name": "House"
		}, {
			"name": "Cabin"
		}, {
			"name": "Church"
		}, {
			"name": "Abandoned"
		}, {
			"name": "Cemetery"
		}, {
			"name": "Infrastructure"
		}, {
			"name": "Machine"
		}, {
			"name": "Car"
		}, {
			"name": "F1"
		}, {
			"name": "Motorcycle"
		}, {
			"name": "Military"
		}, {
			"name": "Gun"
		}, {
			"name": "Knife"
		}, {
			"name": "Boat"
		}, {
			"name": "Rides"
		}, {
			"name": "Destruction"
		}, {
			"name": "ThingsCutInHalf"
		}, {
			"name": "Starship"
		}, {
			"name": "Tool"
		}, {
			"name": "Technology"
		}, {
			"name": "Bridge"
		}, {
			"name": "Police"
		}, {
			"name": "Steam"
		}, {
			"name": "Retail"
		}, {
			"name": "SpaceFlight"
		}, {
			"name": "Animal"
		}, {
			"name": "Human"
		}, {
			"name": "Earthling"
		}, {
			"name": "Adrenaline"
		}, {
			"name": "Climbing"
		}, {
			"name": "Sports"
		}, {
			"name": "Agriculture"
		}, {
			"name": "Tea"
		}, {
			"name": "Bonsai"
		}, {
			"name": "Food"
		}, {
			"name": "Culinary"
		}, {
			"name": "Dessert"
		}, {
			"name": "Design"
		}, {
			"name": "Room"
		}, {
			"name": "AlbumArt"
		}, {
			"name": "Metal"
		}, {
			"name": "MoviePoster"
		}, {
			"name": "TelevisionPoster"
		}, {
			"name": "ComicBook"
		}, {
			"name": "StreetArt"
		}, {
			"name": "Ad"
		}, {
			"name": "Art"
		}, {
			"name": "Fractal"
		}, {
			"name": "Instrument"
		}, {
			"name": "Exposure"
		}, {
			"name": "Macro"
		}, {
			"name": "Micro"
		}, {
			"name": "Geek"
		}, {
			"name": "MTG"
		}, {
			"name": "Gamer"
		}, {
			"name": "PowerWashing"
		}, {
			"name": "Aerial"
		}, {
			"name": "Organization"
		}, {
			"name": "Fashion"
		}, {
			"name": "AV"
		}, {
			"name": "Apocalypse"
		}, {
			"name": "Infrared"
		}, {
			"name": "View"
		}, {
			"name": "Hellscape"
		}, {
			"name": "History"
		}, {
			"name": "Uniform"
		}, {
			"name": "Map"
		}, {
			"name": "Book"
		}, {
			"name": "News"
		}, {
			"name": "Quotes"
		}, {
			"name": "Future"
		}, {
			"name": "Fossil"
		}, {
			"name": "Megalith"
		}, {
			"name": "Artefact"
		}]

	}
})